App/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

  
  
urlpatterns = [  
   path('',views.nope,name='nope'), 
   path('home/',views.home,name='home'), 
   path('register/',views.registerUser,name='register'),
   path('login/',views.LoginUser,name='login'),
    path('logout/', views.logout_request, name= 'logout'),
    path('about-us/',views.About,name="about-us"),
    path('contact-us/',views.Contact,name="contact-us"),
    path('room/<str:pk>/',views.room,name='room'),
    path('create-room/',views.createRoom,name='create-room'),
    path('move',views.move,name='move'),
    path('update-room/<str:pk>/',views.updateRoom,name='update-room'),
    path('delete-room/<str:pk>/',views.deleteRoom,name='delete-room'),
    path('delete-message/<str:pk>/',views.deleteMessage,name='delete-message'),
    path('profile/<str:pk>/',views.userprofile,name='profile'),
    path('update-user/<str:pk>/',views.Update_user,name="update-user"),
    path('topics/',views.Topics_collection,name='topics'),
    path('Recent-Activities/',views.Activity_Page,name='Recent-Activities'),
    
]  
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App.urls')),
]

App/models.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import AbstractUser

# class CustomUser(AbstractUser):
#     # add any custom fields here
#     pass
#model to store user's data coming from contact us form
class contact_us_model(models.Model):
    name=models.CharField(max_length=200,blank=True)
    email=models.EmailField()
    subject=models.CharField(max_length=400,blank=False)
    message = models.TextField(blank=False)
    #date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
       return self.name

class Topic(models.Model):
    name=models.CharField(max_length=300)
    def __str__(self):
        return self.name
    
class Room(models.Model):
    host=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    topic=models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True)
    name=models.CharField(max_length=300)
    participants=models.ManyToManyField(User,related_name='participants',blank=True)
    description=models.TextField(null=True,blank=True)
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering=['-updated','-created']

    def __str__(self):
        return self.name

class Message(models.Model):
    user=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    room=models.ForeignKey(Room,on_delete=models.SET_NULL,null=True)
    body=models.TextField()
    updated=models.DateTimeField(auto_now=True)
    created=models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering=['-updated','-created']

    def __str__(self):
        return self.body[0:45]

App/templates/Login_page.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'style/style.css' %}" />
    <title>StudyBuddy - Find study partners around the world!</title>
  </head>
<img src="{% static 'images/peace2.jpg' %}" height="auto" width="auto"> 
<main class="auth layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Login</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your study partner</h2>

        <form class="form" action="" method="POST">
          {% csrf_token %}
          <div class="form__group form__group">
            <label for="room_name">Username</label>
            <input id="username" name="username" type="text" placeholder="e.g. dennis_ivy" required/>
          </div>
          <div class="form__group">
            <label for="password">Password</label>
            <input
              id="password"
              name="password"
              type="password"
              placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
              required
            />
          </div>

          <button class="btn btn--main" type="submit">
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
              ></path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
              ></path>
            </svg>

            Login
          </button>
        </form>

        <div class="auth__action">
          <p>Haven't signed up yet?</p>
          <a href="{% url 'register' %}" class="btn btn--link">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</main>
</body>
</html>
{% endblock content %} 

App/templates/Update_User.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'style/style.css' %}" />
    <title>StudyBuddy - Find study partners around the world!</title>
  </head>

  <body>
    <main class="update-account layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'profile' user.id %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Edit your profile</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="{% url 'profile' user.id %}" method="POST">
                      {% csrf_token %}
                      <div>
                        {%if messages %}
                         <ul class="messages">
                             {% for message in messages %}
                             <li>
                                 {{message}}
                                 
                             </li>
                         {%endfor%}
                         </ul>
                         {%endif%}
                       </div> 
              <div class="form__group">
                <label for="profile_pic">Avataar</label>
                  <input id="profile_pic" name="profile_pic" type="file" />
              </div>

              <div class="form__group">
                <label for="username">Username</label>
                <input id="username" name="username" type="text" placeholder="E.g. John doe" />
              </div>

              <div class="form__group">
                <label for="email">Email</label>
                <input id="email" name="email" type="text" placeholder="E.g. john@email.com" />
              </div>

                        <div class="form__group">
                            <label for="user_bio">Bio</label>
                            <textarea name="user_bio" id="user_bio" placeholder="Write about yourself..."></textarea>
                        </div>
                        <div class="form__action">
                            <a class="btn btn--dark" href="{% url 'home' %}">Cancel</a>
                            <button class="btn btn--main" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </main>
  </body>
</html>
{% endblock %}

App/templates/about_us.html
{% block content %}
{% load static %}
<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <style>
            
                .img-style{
                  bottom:0;
                  left:0;
                  width:30%;
                  height: 480px;
                  padding:8px;
                  align-content:center;
                  background-color: #404040;
                }
                .info
                {
                
                }
            </style>
    </head>
    <body>
        {% include 'navbar.html' %}
        <img class="img-style" src="{% static 'images/peace2.jpg' %}"><br>
        <div class="info">
        We Are Not Giving Up Until Individuals Dealing With Mental Health Problems Gets Support & Respect!

WHO ARE WE?
Calm Sage is a growing community working towards changing the way individuals think & act about problems related to Mental Health. Managed by the current generation, it’s a dedicated project to help people calm their minds & heal their lives through motivational words, graphics, podcasts, webinars, open-discussions & personal chats.

Here, at Calm Sage, we want you to know You Are Not Alone. We are here to take your mind at a peaceful place, no matter what is happening around you.

We offer comprehensive content all devoted to self-improvement with a focus on personal productivity, inspiration and self-education. We offer our audience a platform to share their real-life struggles & inspiring stories that can be published & get connected with people who are affected by problems like stress, anxiety, trauma, and depression.

OUR AIM
Calm Sage diverges from traditional ‘Self Help’ by taking a broader approach. Rather than sticking to a small set of topics to deal with mental illness & other issues. The platform addresses important steps you can take in the coping process & even have effective action plans for recovery. Calm Sage is a place where individuals can overcome their day-to-day challenges in a stigma-free environment. While we aspire of a progressive society & culture, we intend to impart practices where mental health taboos & issues can be discussed openly & managed effectively with emotional and professional assistance.

OUR MISSION
Calm Sage strives to bring billions of smiles every day. It is our mission to improve overall mental and physical wellbeing & reduce discrimination towards individuals dealing with mental problems. We also aim to form a collaborative social structure with a sole goal to promote happiness, channel positivity, and strengthen your soul.
        </div>   
</body>
    </html>
{% endblock content %}

App/templates/activity.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<head>

  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
  <link rel="stylesheet" href="{% static 'style/style.css' %}"/>
  <title>StudyBuddy - Find study partners around the world!</title>
 
</head>

        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Current Activities</h3>
            </div>
          </div>
       

          <div class="activities-page layout__body">
            {% for msg in room_messages%}
            <div class="activities__box">
              <div class="activities__boxHeader roomListRoom__header">
                <a href="{%  url 'profile' user.id %}" class="roomListRoom__author">
                  <div class="avatar avatar--small active">
                    <img src="{% static 'images/user.png' %}" />
                  </div>
                  <p>
                    {{msg.user}}
                    <span>{{msg.created | timesince}} ago</span>
                  </p>
                </a>
              {% if request.user  == msg.user %}
                <div class="roomListRoom__actions">
                  <a href="{% url 'delete-message' msg.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                      ></path>
                    </svg>
                  </a>
                </div>
                {% endif %}
              </div>
              <div class="activities__boxContent">
                <p>replied to: <a href="{% url 'room' msg.id %}">{{msg.room}}</a>”</p>
                <div class="activities__boxRoomContent">
                {{msg.body}}
                </div>
              </div>
            </div>
            {% endfor %}
      

          </div>
        </div>
    

{% endblock content %}

App/templates/activity_component.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<head>

  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
  <link rel="stylesheet" href="{% static 'style/style.css' %}"/>
  <title>StudyBuddy - Find study partners around the world!</title>
 
</head>
      <div class="activities-page layout__body">
        <h3>Recent Activities</h3>
        {% for msg in room_messages%}
        
        <div class="activities__box">
          <div class="activities__boxHeader roomListRoom__header">
            <a href="{%  url 'profile' user.id %}" class="roomListRoom__author">
              <div class="avatar avatar--small active">
                <img src="{% static 'images/user.png' %}" />
              </div>
              <p>
                {{msg.user}}
                <span>{{msg.created | timesince}} ago</span>
              </p>
            </a>
          {% if request.user  == msg.user %}
            <div class="roomListRoom__actions">
              <a href="{% url 'delete-message' msg.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                  ></path>
                </svg>
              </a>
            </div>
            {% endif %}
          </div>
          <div class="activities__boxContent">
            <p>replied to: <a href="{% url 'room' msg.id %}">{{msg.room}}</a>”</p>
            <div class="activities__boxRoomContent">
            {{msg.body}}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
       
    </div>
  </div>
   
 
{%endblock %}
</body>
</html>

App/templates/base.html
<!doctype html>  
{%block content %}
{% load static %}
<html lang="en">  
  <head>  
    <!-- Required meta tags -->  
    <meta charset="utf-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1">  
 
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'style/style.css' %}" />
    <title>StudyBuddy - Find study partners around the world!</title>
  
    <!-- Bootstrap CSS -->  
  </head>  
  <body>  
 
  {% include 'navbar.html' %}
    <div>
      
      {%if messages %}
       <ul class="messages">
           {% for message in messages %}
           <li>
               {{message}} 
           </li>
           
       {%endfor%}
       </ul>
       {%endif%}
     </div> 
    {% endblock content %}  
  </body>  
</html>  

App/templates/delete.html
{% extends 'base.html' %}
{% block content %} 
{% load static %}
<html lang="en">
   <head>
   
      <meta charset="UTF-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
      <link rel="stylesheet" href="{% static 'style/style.css'%}" />
      <title>StudyBuddy - Find study partners around the world!</title>
      <script src="{% static 'js/script.js' %}"></script>
   </head>

    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                       <a href="{{request.META.HTTP_REFERER}}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Move Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    
                    <form class="form" action="" method="POST">
                     {%csrf_token%}
                        <div class="form__group">
                            <p>Are you sure you want to delete?</p>
                        </div>
                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
    <script src="{% static 'js/script.js' %}"></script>
{% endblock content %}

App/templates/feed_components.html
{%load static %}
{% extends 'base.html' %}
{% block content %}
<div>
  <hr>
  {% for room in rooms %}
  <hr>

<div class="roomListRoom">
<div class="roomListRoom__header">
<a href="" class="roomListRoom__author">
  <div class="avatar avatar--small">
    <img src="{% static 'images/user.png' %}" />
  </div>
  <span>@{{room.host.username}}</span>
</a>
<div class="roomListRoom__actions">
  <span>{{room.created|timesince}} ago </span>
</div>
</div>
<div class="roomListRoom__content">
<a href="{% url 'room' room.id %}">{{room.name}}</a>
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur ducimus harum dolorem, obcaecati
  mollitia omnis quasi aut consequuntur enim itaque labore.
</p>
</div>

<div class="roomListRoom__meta">
<a href="{% url 'room' room.id %}" class="roomListRoom__joined">
  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
    <title>user-group</title>
    <path
      d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
    ></path>
    <path
      d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
    ></path>
    <path
      d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
    ></path>
    <path
      d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
    ></path>
  </svg>
  {{room.participants.all.count}} Joined
</a>
<p class="roomListRoom__topic">{{room.topic.name}}</p>
</div><br>

</div>
{%endfor %}
</div>
{% endblock content %}

App/templates/navbar.html
{%block content %}
{% load static %}
<html lang="en">  
  <head>  
    <!-- Required meta tags -->  
    <meta charset="utf-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1">  
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="{% static 'assets/favicon.ico'%}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'style/style.css' %}" />
    <script src="{% static "js/script.js" %}"></script>
    <title>StudyBuddy - Find study partners around the world!</title>
  
    <!-- Bootstrap CSS -->  
  </head>  
<header class="header header--loggedIn">
  <div class="container">
    <a href="/" class="header__logo">
      <img src="{% static 'images/logo.svg'%}" />
      <h1>StudyBuddy</h1>
    </a>
    <form class="header__search" method="GET" action="{% url 'home' %}">
      <label>
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>search</title>
          <path
            d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
          ></path>
        </svg>
        <input type="text"  name="q" placeholder="Search for rooms..."/>
      </label>
    </form>
    <nav class="header__menu">
      {% if request.user.is_authenticated %}
      <div class="header__user">
            <div class="avatar avatar--medium active">
            <img src="{% static 'images/user.png' %}" />
          </div>
          <p>{{request.user}}<span>{{request.user.username}}</span></p>
          
      
        <button class="dropdown-button">
          <a href="{% url 'profile' user.id %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>chevron-down</title>
            <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
          </svg></a>
        </button>
    
      </div>
      {% else %}
      <!-- Not Logged In -->
      <a href="{% url 'login' %}">
        <img src="{% static 'images/user.png' %}" />
        <p>Login</p>
      </a> 
      {% endif %}
      <div class="dropdown-menu">
        <a href="" class="dropdown-link">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>tools</title>
            <path
              d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z"
            ></path>
          </svg>
          Settings</a>
     
        <a href="{% url 'logout' %}" class="dropdown-link"
          ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>sign-out</title>
            <path
              d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z"
            ></path>
            <path
              d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z"
            ></path>
          </svg>
          Logout</a
        >
      </div>
    </nav>
  </div>
</header>
{%endblock content %}

App/templates/topics_components.html
{% extends 'base.html' %}
{% block content %}
<div class="topics">
  <div class="topics__header">
    <h2>Browse Topics for Self-Care</h2>
  </div>
  <ul class="topics__list">
      <ul type="square">
    <li>
      <a href="{% url 'home' %}" class="active">Total Topics Provided <span>{{topics.count}}</span></a>
    </li>
   {% for x in topics %} 
    <li>
      <a href="{% url 'home' %}?q={{x.name}}">{{x.name}} <span>{{x.room_set.all.count}}</span></a>
    </li>
    {% endfor %}
  </ul>
  </ul>
  <a class="btn btn--link" href="{% url  'topics' %}">
    More
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
      <title>chevron-down</title>
      <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
    </svg>
  </a>
</div>
<!-- Topics End -->   

{% endblock content %}